#!/usr/bin/env python3

import sys

map = []
map_size = 0

def add_opposite_play_to(coord):
    print(coord)
    if (coord != "DONE"):
        list_coord = coord.split(",")
        if (len(list_coord) != 3):
            map[int(list_coord[0]) - 1][int(list_coord[1]) - 1] = '2'
        else:
            map[int(list_coord[0]) - 1][int(list_coord[1]) - 1] = list_coord[2]

def process_command(command_array):
    if (command_array[0] == "TURN"):
        add_opposite_play_to(command_array[1])
        #algo_min_max
    elif (command_array[0] == "BOARD"):
        while (command_array != "DONE"):
            command_array = input()
            add_opposite_play_to(command_array)
    elif (command_array[0] == "BEGIN"):
        print(command_array)
        # First move
    elif (command_array[0] == "ABOUT"):
        print("name=\"ui\", version=\"0.1.1\", author=\"Mananka && legau1000\", country=\"FRANCE\"")
    print(map)

def create_map(map_size):
    i = 0
    while (i < map_size):
        map.append(['0'] * map_size)
        i += 1
    print("OK - everything is good")

def SplitInput():
    command = input()
    command_array = command.split(" ")
    if (command_array[0] == "END"):
        sys.exit(0)
    return (command_array)

def main():
    end = 0
    command_array = SplitInput()
    if (command_array[0] == "START"):
        map_size = int(command_array[1])
        create_map(map_size)
    else:
        sys.exit(84)
    while (end != 1):
        command_array = SplitInput()
        process_command(command_array)
    sys.exit(0)

if __name__ == "__main__":
    main()